In [1]:
import kagglehub
path = kagglehub.dataset_download("umeradnaan/extinction-of-a-species-data")

Downloading to /root/.cache/kagglehub/datasets/umeradnaan/extinction-of-a-species-data/1.archive...

100%|██████████| 5.29M/5.29M [00:01<00:00, 4.46MB/s]

Extracting files...

In [2]:
import os

# List the contents of the downloaded directory
print(os.listdir(path))

['extinct_species_dataset.csv']

In [3]:
import pandas as pd

df = pd.read_csv(os.path.join(path, 'extinct_species_dataset.csv'))
df.head()

     Species Name  Years Lived (Million Years) Extinction Reason
0       Trilobite                       337.75      Human Impact
1        Smilodon                       311.57  Natural Disaster
2            Dodo                        67.49   Mass Extinction
3  Woolly Mammoth                        89.81   Asteroid Impact
4  Woolly Mammoth                       395.72    Climate Change

In [4]:
print(df.info())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 3 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   Species Name                 1000000 non-null  object
 1   Years Lived (Million Years)  1000000 non-null  float64
 2   Extinction Reason            1000000 non-null  object
dtypes: float64(1), object(2)
memory usage: 22.9+ MB
None
Species Name                   0
Years Lived (Million Years)    0
Extinction Reason              0
dtype: int64

In [5]:
df_encoded = pd.get_dummies(df, columns=['Species Name', 'Extinction Reason'], drop_first=True)
df_encoded.head()

,Years Lived (Million Years),Species Name_Megalodon,Species Name_Plesiosaur,Species Name_Quagga,Species Name_Sabertooth Tiger,Species Name_Smilodon,Species Name_Steller’s Sea Cow,Species Name_Trilobite,Species Name_Tyrannosaurus Rex,Species Name_Woolly Mammoth,Extinction Reason_Climate Change,Extinction Reason_Habitat Loss,Extinction Reason_Human Impact,Extinction Reason_Mass Extinction,Extinction Reason_Natural Disaster,Extinction Reason_Predation
0,337.75,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False
1,311.57,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False
2,67.49,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
3,89.81,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
4,395.72,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False

In [6]:
from sklearn.model_selection import train_test_split

# Separate features (X) and target (y)
X = df_encoded.drop(columns=[col for col in df_encoded.columns if 'Extinction Reason' in col])
y = df_encoded[[col for col in df_encoded.columns if 'Extinction Reason' in col]]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (800000, 10)
y_train shape: (800000, 6)
X_test shape: (200000, 10)
y_test shape: (200000, 6)

In [7]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Define the model architecture
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),  # Input layer with the number of features
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(y_train.shape[1], activation='softmax') # Output layer with number of target classes
])

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         1,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 6)              │           390 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,054 (39.27 KB)

 Trainable params: 10,054 (39.27 KB)

 Non-trainable params: 0 (0.00 B)

In [9]:
history = model.fit(X_train, y_train,
                    epochs=1,  # You can adjust the number of epochs
                    batch_size=32, # You can adjust the batch size
                    validation_split=0.2, # Use 20% of training data for validation
                    verbose=1)

20000/20000 ━━━━━━━━━━━━━━━━━━━━ 31s 2ms/step - accuracy: 0.1659 - loss: 7622.8345 - val_accuracy: 0.2850 - val_loss: 6327.6963

In [10]:
# Save the trained model
model.save('extinction_reason_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Now that the model is saved, I will create the Streamlit application. First, I'll install the necessary library.

In [11]:
# Install Streamlit
!pip install streamlit -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 37.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 60.9 MB/s eta 0:00:00

Next, I'll create a Python file for the Streamlit application. This app will allow users to input species data and get predictions for the extinction reason.

In [12]:
import streamlit as st
import pandas as pd
import tensorflow as tf
import numpy as np

# Load the trained model
model = tf.keras.models.load_model('extinction_reason_model.h5')

# Get the feature names from the training data (excluding target columns)
# This is crucial to ensure consistent input order for prediction
# Assuming X_train has the correct column order
X_train_columns = X_train.columns.tolist()

# Define all possible species names and extinction reasons used during training
# These need to match the columns created by pd.get_dummies
all_species_names = [col.replace('Species Name_', '') for col in df_encoded.columns if 'Species Name_' in col]
all_species_names = ['Trilobite'] + all_species_names # Add one of the original species as a base for drop_first=True

all_extinction_reasons_encoded_cols = [col for col in df_encoded.columns if 'Extinction Reason_' in col]
all_extinction_reasons = [col.replace('Extinction Reason_', '') for col in all_extinction_reasons_encoded_cols]
all_extinction_reasons = ['Human Impact'] + all_extinction_reasons # Add one of the original reasons as a base for drop_first=True

# Streamlit app layout
st.title('Extinction Reason Predictor')
st.write('Enter the details of a species to predict its extinction reason.')

# Input fields
species_name_input = st.selectbox('Species Name', all_species_names)
years_lived_input = st.number_input('Years Lived (Million Years)', min_value=0.0, value=100.0, step=0.1)

# Prepare input for prediction
if st.button('Predict Extinction Reason'):
    # Create an empty DataFrame with all feature columns from training data
    input_df = pd.DataFrame(0, index=[0], columns=X_train_columns)

    # Fill in 'Years Lived (Million Years)'
    input_df['Years Lived (Million Years)'] = years_lived_input

    # Fill in one-hot encoded species name
    if species_name_input != 'Trilobite': # 'Trilobite' would be the reference (dropped_first=True)
        col_name = f'Species Name_{species_name_input}'
        if col_name in input_df.columns:
            input_df[col_name] = True

    # Make prediction
    prediction = model.predict(input_df)
    predicted_class_index = np.argmax(prediction, axis=1)[0]

    # Map the predicted index back to the extinction reason
    # The order of y.columns is important here
    predicted_extinction_reason_col = y.columns[predicted_class_index]
    predicted_reason = predicted_extinction_reason_col.replace('Extinction Reason_', '')

    st.success(f'The predicted extinction reason is: **{predicted_reason}**')

# To run this app, save it as a .py file (e.g., app.py) and run `streamlit run app.py` in your terminal.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
2026-08-17 12:38:40.543 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.006
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py [ARGUMENTS]
2026-08-17 12:38:41.007 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.008 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.009 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.009 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.010 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.011 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.012 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.013 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.013 Session state does not function when running a script without `streamlit run`
2026-08-17 12:38:41.014 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.016 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.016 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.017 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.018 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.018 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.020 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.021 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.021 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.022 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.023 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.024 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.025 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-17 12:38:41.025 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [25]:
import shutil
import os

# The 'path' variable holds the directory where kagglehub downloaded the dataset.
# The CSV file is inside this directory.
source_file_path = os.path.join(path, 'extinct_species_dataset.csv')
destination_file_path = '/content/extinct_species_dataset.csv'

# Copy the dataset to /content/ so the app.py can access it.
shutil.copy(source_file_path, destination_file_path)
print(f"Successfully copied '{source_file_path}' to '{destination_file_path}'")

Successfully copied '/root/.cache/kagglehub/datasets/umeradnaan/extinction-of-a-species-data/versions/1/extinct_species_dataset.csv' to '/content/extinct_species_dataset.csv'

In [28]:
%%writefile app.py
import streamlit as st
import pandas as pd
import tensorflow as tf
import numpy as np
import os

# Load the trained model
model = tf.keras.models.load_model('extinction_reason_model.h5')

# --- Re-load and preprocess data within the Streamlit app context ---
csv_path = '/content/extinct_species_dataset.csv'
df = pd.read_csv(csv_path)
df_encoded = pd.get_dummies(df, columns=['Species Name', 'Extinction Reason'], drop_first=True)

X_columns_for_app = df_encoded.drop(columns=[col for col in df_encoded.columns if 'Extinction Reason' in col]).columns.tolist()
y_columns_for_app = [col for col in df_encoded.columns if 'Extinction Reason' in col]

all_species_names_from_df = df['Species Name'].unique().tolist()
all_extinction_reasons_from_df = [col.replace('Extinction Reason_', '') for col in y_columns_for_app]

# Streamlit app layout
st.set_page_config(layout="centered") # Set layout to wide if preferred
st.title('🌍 Extinction Reason Predictor 🦖')
st.write('Enter the details of a species to predict its extinction reason.')

# Input fields in the sidebar
with st.sidebar:
    st.header('Input Parameters 📊')
    species_name_input = st.selectbox('Species Name', all_species_names_from_df)
    years_lived_input = st.number_input('Years Lived (Million Years)', min_value=0.0, value=100.0, step=0.1)

    # Prepare input for prediction
    if st.button('Predict Extinction Reason'):
        # Create an empty DataFrame with all feature columns in the correct order
        input_df = pd.DataFrame(0, index=[0], columns=X_columns_for_app)

        # Fill in 'Years Lived (Million Years)'
        input_df['Years Lived (Million Years)'] = years_lived_input

        # Fill in one-hot encoded species name
        if species_name_input != all_species_names_from_df[0]: # If the input is not the baseline category
            col_name = f'Species Name_{species_name_input}'
            if col_name in input_df.columns:
                input_df[col_name] = 1 # Use 1 for True in DataFrame

        # Make prediction
        prediction = model.predict(input_df)
        predicted_class_index = np.argmax(prediction, axis=1)[0]

        # Map the predicted index back to the extinction reason
        predicted_extinction_reason_col = y_columns_for_app[predicted_class_index]
        predicted_reason = predicted_extinction_reason_col.replace('Extinction Reason_', '')

        st.success(f'The predicted extinction reason is: **{predicted_reason}**')

st.markdown("""
---
This application predicts the most likely reason for a species' extinction based on its name and how long it lived.
""")

Overwriting app.py

Now that any previous instances are stopped, I will run the Streamlit app again and expose it via a public URL using `ngrok`.

Now, run the Streamlit app using the following command. After executing, click on the public URL that appears to interact with the app.

In [15]:
!pip install --ignore-installed blinker
!pip install streamlit

Collecting blinker
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Installing collected packages: blinker
Successfully installed blinker-1.9.0

Requirement already satisfied: streamlit in /usr/local/lib/python3.12/dist-packages (1.61.1)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.4.2)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.9.3)
Requirement already satisfied: protobuf<8,>=5.26.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow<25,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.16.0)
Requirement already satisfied: starlette<1.4.0,>=0.46.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.3.1)
Requirement already satisfied: uvicorn<1,>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.51.0)
Requirement already satisfied: httptools<1,>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.14.2)
Requirement already satisfied: python-multipart<1,>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<17,>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2.24.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=4.0.0->streamlit) (3.18)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.6.17)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2026.6.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)

In [16]:
!pip install streamlit pyngrok

Requirement already satisfied: streamlit in /usr/local/lib/python3.12/dist-packages (1.61.1)
Collecting pyngrok
  Downloading pyngrok-8.1.2-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.4.2)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.9.3)
Requirement already satisfied: protobuf<8,>=5.26.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow<25,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.16.0)
Requirement already satisfied: starlette<1.4.0,>=0.46.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.3.1)
Requirement already satisfied: uvicorn<1,>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.51.0)
Requirement already satisfied: httptools<1,>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.14.2)
Requirement already satisfied: python-multipart<1,>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<17,>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2.24.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=4.0.0->streamlit) (3.18)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.6.17)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2026.6.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading pyngrok-8.1.2-py3-none-any.whl (25 kB)
Installing collected packages: pyngrok
Successfully installed pyngrok-8.1.2

In [17]:
from pyngrok import ngrok
ngrok.set_auth_token("3H2nxZtP4iC5L9tX9K97OPLut9W_4JsZrRVF5aRFQpQCCePy1")

In [29]:
from pyngrok import ngrok

public_url = ngrok.connect(8501)
print(public_url)

NgrokTunnel: "https://vanity-amperage-commodore.ngrok-free.dev" -> "http://localhost:8501"

In [30]:
# Run the Streamlit app
# This will provide a public URL to access the app
!streamlit run app.py &

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

WARNING:pyngrok.process.ngrok:t=2026-08-17T12:47:59+0000 lvl=warn msg="failed to open private leg" id=fe1172757cfa privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-08-17T12:47:59+0000 lvl=warn msg="failed to open private leg" id=36065382a1ec privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"

2026-08-17 12:48:00.147 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.81.223.96:8501

2026-08-17 12:48:08.388935: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7f1565a11ee0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7f1565a11ee0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
  Stopping...

In [14]:
!streamlit run app.py &>/dev/null&  # Run in background to avoid blocking the cell
!npx localtunnel --port 8501

⠙⠹⠸⠼⠴⠦⠧Need to install the following packages:
localtunnel@2.0.2
Ok to proceed? (y) ^C